const RECEIVED_SHELVES = 'RECEIVED_SHELVES';
const REQUEST_BOOKS = 'REQUEST_BOOKS';
const RECEIVED_BOOKS = 'RECEIVED_BOOKS';
const UPDATE_CURRENT_BOOKS = 'UPDATE_CURRENT_BOOKS';

const MAX_BOOKS_PER_PAGE = 20;

export { RECEIVED_SHELVES, REQUEST_BOOKS, RECEIVED_BOOKS,
	UPDATE_CURRENT_BOOKS, MAX_BOOKS_PER_PAGE
};